type Book {
  title: String!
  author: String!
}

type Query {
  books: [Book]!
}

input BookInput {
  title: String!
  author: String!
}

type BookPayload {
  title: String!
  author: String!
}

type Mutation {
  addBook(input: BookInput!): BookPayload!
  deleteBook(id: ID!): BookPayload!
  updateBook(id: ID!, input: BookInput!): BookPayload!
}